export const ADD_EVENT_SAGA = 'ADD_EVENT_SAGA'
export const GET_EVENT_SAGA = 'GET_EVENT_SAGA'
export const GET_EVENT ="GET_EVENT"
export const ADD_EVENT ="ADD_EVENT"
export const CHANGE_MODAL_VISIBILITY = "CHANGE_MODAL_VISIBILITY"
export const ADD_EVENT_MODAL = 'ADD_EVENT_MODAL'
